site_name: User Guide for mstdn.party / mstdn.plus
theme:
  name: material
  features:
    - navigation.expand
    - content.tooltips
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
nav:
  - index.md
  - 'Another Guide to Mastodon':
    - prologue.md
    - should-i.md
    - how-to-follow.md
    - best-practices.md
  - 'Instance-specific information':
    - rules.md
    - 'Miscellaneous': misc.md
    - 'For other federating instances': federation.md